package org.geo7.enums;

public enum NomeCategoria {
    PRODUTO_VEGETAL_ISOLADO,
    PRODUTO_VEGETAL_CONSORCIO_OU_ROTACAO,
    AREAS_DE_EXPLORACAO_ACRICOLA_OU_GRANJEIRA,
    AREAS_COM_OUTRO_USO,
    AREAS_COM_RESTRICAO,
    AREAS_DE_PASTAGEM,
    INFOMACOES_SOBRE_PECUARIA,
    AREAS_SEM_RESTICAO_E_SEM_USO,
    LOCALIZACAO_E_DATA
}
